# Site settings
title: GDS operations open source
email: gds-operations-open-source@digital.cabinet-office.gov.uk
description: "Open source software from the UK Government Digital Service"
baseurl: ""
url: "https://github.com/gds-operations"

# Build settings
markdown: redcarpet
permalink: pretty
