# Site settings
title: GDS Operations open source
email: gds-operations-open-source@digital.cabinet-office.gov.uk
description: "Open source software from the UK Government Digital Service"
baseurl: ""
url: "https://github.com/gds-operations"
github_org: gds-operations
github_user_id: 4703760
twitter_username: gdsteam

# Build settings
markdown: redcarpet
permalink: pretty
exclude: [ "vendor/" ]
